import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
import { PGlite } from '@electric-sql/pglite'
import { dataPlan } from '../server/dataPolicy.js'
import { requireSession, hashToken, checkOrigin, startSession } from '../server/auth.js'

test('session requires a valid cookie, expiry and password version', async () => {
  const token='a'.repeat(64), password='synthetic-hash'
  const req={headers:{cookie:'hb_session='+token,host:'example.test',origin:'https://example.test'}}
  const makeDb=(session,user) => ({from(table) {
    const builder={select(){return this},eq(){return this},gt(){return this},
      async maybeSingle(){return {data:table==='app_sessions'?session:user,error:null}}}
    return builder
  }})
  await assert.rejects(()=>requireSession({headers:{}},makeDb(null,null)),e=>e.status===401)
  await assert.rejects(()=>requireSession(req,makeDb(null,null)),e=>e.status===401)
  const user={username:'test',household_id:'test-household',display_name:'Test',password}
  await assert.rejects(()=>requireSession(req,makeDb({username:'test',password_version:'old'},user)),e=>e.status===401)
  const valid=await requireSession(req,makeDb({username:'test',password_version:hashToken(password)},{...user}))
  assert.equal(valid.user.password,undefined)
  assert.throws(()=>checkOrigin({headers:{host:'example.test',origin:'https://other.test'}}),e=>e.status===403)
  const headers={},writes=[]
  await startSession({from(){return {async insert(v){writes.push(v);return {error:null}}}}},
    {setHeader(k,v){headers[k]=v}},'test',password)
  assert.match(headers['Set-Cookie'],/HttpOnly; SameSite=Strict/)
  assert.equal(writes[0].password_version,hashToken(password))
  assert.ok(!headers['Set-Cookie'].includes(writes[0].token_hash))
})

test('gateway rejects unsafe queries and forces verified household',()=>{
 const user={household_id:randomUUID()}
 const plan=dataPlan({table:'assets',method:'POST',body:{name:'test',amount:5,household_id:'forged'}},user)
 assert.equal(plan.values.household_id,user.household_id)
 assert.equal(plan.scope,user.household_id)
 for(const input of [
  {table:'app_users'},
  {table:'assets',params:[['select','*,households(*)']]},
  {table:'assets',method:'PATCH',body:{owner:'x'}},
  {table:'transactions',method:'POST',body:{amount:10}},
  {table:'assets',method:'POST',body:{id:1,amount:10}},
 ]) assert.throws(()=>dataPlan(input,user))
})

test('Postgres atomic transfers, authorization, retries and invitations',async()=>{
 const db=new PGlite()
 try {
 await db.exec(`
 create role anon;
 create role authenticated;
 create role service_role bypassrls;
 create table households(id uuid primary key default gen_random_uuid(),dating_start date,wedding_date date,categories jsonb);
 create table app_users(username text primary key,password text,display_name text,partner_name text,household_id uuid references households);
 create table assets(id bigint generated by default as identity primary key,household_id uuid references households,amount numeric,category text,owner text,updated_at timestamptz,deleted_at timestamptz);
 create table transactions(id bigint generated by default as identity primary key,date date,type text,category text,amount numeric,memo text,owner text,author text,household_id uuid references households,linked_asset_id bigint references assets);
 `)
 for(const file of ['020_security_prepare.sql','021_atomic_operations.sql']) await db.exec(await readFile(new URL('../sql/'+file,import.meta.url),'utf8'))
 for(let i=0;i<2;i++) await db.exec(await readFile(new URL('../sql/025_transaction_undo.sql',import.meta.url),'utf8'))
 // The rate-limit table must be created by the migration, not assumed by fixtures.
 await db.exec(await readFile(new URL('../sql/023_login_attempts_repair.sql',import.meta.url),'utf8'))
 await db.exec(await readFile(new URL('../sql/023_login_attempts_repair.sql',import.meta.url),'utf8'))
 const h=randomUUID(),other=randomUUID()
 await db.query('insert into households(id) values($1),($2)',[h,other])
 await db.query("insert into app_users values('a','hash','A','B',$1),('b','hash','B','A',$1),('c','hash','C','D',$2)",[h,other])
 await db.query("insert into assets(id,household_id,amount,category,owner) values(1,$1,1000,'현금','A'),(2,$1,900,'비상금','B'),(3,$2,100,'현금','C')",[h,other])
 const mutate=async(actor,action,id,fields,request=randomUUID())=>(await db.query('select hb_mutate_transaction($1,$2,$3,$4::jsonb,$5) as result',[actor,action,id,JSON.stringify(fields),request])).rows[0].result
 const req=randomUUID(),fields={date:'2026-10-02',type:'expense',category:'배우자 이체',amount:100,owner:'A',linked_asset_id:1}
 const first=await mutate('a','add',null,fields,req)
 assert.equal(first.rows.length,2)
 assert.equal(first.rows[0].transfer_id,first.rows[1].transfer_id)
 assert.equal(first.rows.find(r=>r.type==='income').category,'배우자 이체')
 await mutate('a','add',null,fields,req)
 assert.equal((await db.query('select count(*)::int n from transactions')).rows[0].n,2)
 assert.equal(Number((await db.query('select amount from assets where id=1')).rows[0].amount),1100)
 await assert.rejects(()=>mutate('a','add',null,{...fields,amount:200},req))
 await assert.rejects(()=>mutate('c','delete',first.primary.id,{}))
 for(const asset of [2,3]) await assert.rejects(()=>mutate('a','add',null,{...fields,linked_asset_id:asset}))
 assert.equal((await db.query('select count(*)::int n from transactions')).rows[0].n,2)
 const receiver=first.rows.find(r=>r.type==='income')
 const edited=await mutate('b','update',receiver.id,{amount:200,date:'2026-09-30'})
 assert.ok(edited.rows.every(r=>Number(r.amount)===200&&r.date==='2026-09-30'))
 assert.equal(Number((await db.query('select amount from assets where id=1')).rows[0].amount),1200)
 const removed=await mutate('b','delete',receiver.id,{})
 assert.equal(removed.removedIds.length,2)
 assert.equal((await db.query('select count(*)::int n from transactions')).rows[0].n,0)
 assert.equal(Number((await db.query('select amount from assets where id=1')).rows[0].amount),1000)
 await assert.rejects(()=>mutate('a','undo',null,{delete_request:removed.deleteRequest}))
 const undoRequest=randomUUID()
 const restored=await mutate('b','undo',null,{delete_request:removed.deleteRequest},undoRequest)
 assert.equal(restored.rows.length,2)
 assert.deepEqual(restored.rows.map(r=>r.id).sort(),removed.removedIds.sort())
 assert.equal(Number((await db.query('select amount from assets where id=1')).rows[0].amount),1200)
 await mutate('b','undo',null,{delete_request:removed.deleteRequest},undoRequest)
 assert.equal((await db.query('select count(*)::int n from transactions')).rows[0].n,2)
 await assert.rejects(()=>mutate('b','undo',null,{delete_request:removed.deleteRequest}))
 const again=await mutate('b','delete',receiver.id,{})
 await db.query('update assets set deleted_at=now() where id=1')
 await assert.rejects(()=>mutate('b','undo',null,{delete_request:again.deleteRequest}))
 assert.equal((await db.query('select count(*)::int n from transactions')).rows[0].n,0)
 assert.equal(Number((await db.query('select amount from assets where id=1')).rows[0].amount),1000)
 await db.query('update assets set deleted_at=null where id=1')
 await db.query("update app_mutation_requests set created_at=now()-interval '11 minutes' where request_id=$1",[again.deleteRequest])
 await assert.rejects(()=>mutate('b','undo',null,{delete_request:again.deleteRequest}))
 await db.query("insert into transactions(date,type,category,amount,owner,household_id) values('2026-10-02','income','배우자 이체',50,'B',$1)",[h])
 assert.equal((await db.query('select transfer_id from transactions')).rows[0].transfer_id,null)
 const signup=async(name,invite)=>(await db.query("select hb_signup($1,'hash',$1,'partner','2026-01-01','dating','{}'::jsonb,$2)",[name,invite]))
 await signup('solo',null)
 const solo=(await db.query("select household_id from app_users where username='solo'")).rows[0].household_id
 await db.query("insert into household_invites(token_hash,household_id,created_by,expires_at) values('invite',$1,'solo',now()+interval '1 hour')",[solo])
 await assert.rejects(()=>signup('a','invite'))
 assert.equal((await db.query("select used_at from household_invites where token_hash='invite'")).rows[0].used_at,null)
 await signup('partner','invite')
 assert.equal((await db.query("select household_id from app_users where username='partner'")).rows[0].household_id,solo)
 await assert.rejects(()=>signup('third','invite'))
 await signup('separate',null)
 assert.notEqual((await db.query("select household_id from app_users where username='separate'")).rows[0].household_id,solo)
 assert.equal((await db.query("select hb_rate_limit('test',1) ok")).rows[0].ok,true)
 assert.equal((await db.query("select hb_rate_limit('test',1) ok")).rows[0].ok,false)
 await db.exec('set role anon')
 await assert.rejects(()=>db.query("select hb_rate_limit('test',1)"))
 await assert.rejects(()=>db.query('select * from app_sessions'))
 await db.exec('reset role')
 await db.exec("create table recurring_templates(id bigint generated always as identity primary key); create table net_worth_snapshots(id bigint generated always as identity primary key)")
 await db.exec("insert into app_sessions(token_hash,username,expires_at,password_version) values('synthetic','a',now()+interval '1 hour','version')")
 await db.exec(await readFile(new URL('../sql/022_lockdown.sql',import.meta.url),'utf8'))
 for(const role of ['anon','authenticated']) {
   await db.exec('set role '+role)
   for(const table of ['transactions','assets','households','app_users','recurring_templates','net_worth_snapshots']) {
     await assert.rejects(()=>db.query('select * from '+table),e=>e.code==='42501')
   }
   await db.exec('reset role')
 }
 await db.exec('set role service_role')
 assert.equal((await db.query('select count(*)::int n from transactions')).rows[0].n,1)
 } finally { await db.close() }
})

