export const CATEGORIES = {
  income: ['월급', '용돈', '부수입', '기타수입'],
  expense: [
    '식비',
    '생활비',
    '교통',
    '주거/통신',
    '쇼핑',
    '의료',
    '보험',
    '문화/여가',
    '교육',
    '카드값',
    '적금(주택청약)',
    '적금(연금저축)',
    '적금(ISA계좌)',
    '기타지출',
  ],
}

export const EXPENSE_CATEGORY_COLORS = {
  식비: '#ffb3c6',
  생활비: '#ffdac1',
  교통: '#ffd6a5',
  '주거/통신': '#fdffb6',
  쇼핑: '#caffbf',
  의료: '#9bf6ff',
  보험: '#c8b6ff',
  '문화/여가': '#a0c4ff',
  교육: '#bdb2ff',
  카드값: '#ffc6ff',
  '적금(주택청약)': '#fdffb6',
  '적금(연금저축)': '#9bf6ff',
  '적금(ISA계좌)': '#ffd6e8',
  기타지출: '#e0c3cf',
}
